config/routes.rb
Tridb::Application.routes.draw do
  resources :import_results_from_urls

  resources :import_short_ftp_triathlons

  resources :competitions

  resources :team_years

  resources :teams

  resources :classifications

  resources :segment_results

  resources :segments

  resources :sports

  resources :results

  resources :athletes

  resources :races

  

end

app/models/age_category.rb
class AgeCategory < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/age_group.rb
class AgeGroup < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :segment_results
  has_many :team_years
  belongs_to :locations
  belongs_to :teams
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :results
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/global_race.rb
class GlobalRace < ActiveRecord::Base
  has_many :races
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :races
  has_many :athletes
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :locations
  belongs_to :competitions
  belongs_to :sports
  belongs_to :race_types
  belongs_to :global_races
  has_many :segments
  has_many :results
end

app/models/race_type.rb
class RaceType < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :races
  belongs_to :athletes
  belongs_to :classification
  belongs_to :age_group
  belongs_to :age_category
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  has_many :segment_results
  belongs_to :races
  belongs_to :sports
end

app/models/segment_result.rb
class SegmentResult < ActiveRecord::Base
  belongs_to :segments
  belongs_to :athletes
  belongs_to :age_groups
  belongs_to :age_category
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :segments
  has_many :races
  has_many :competitions
  has_many :race_types
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :athletes
  has_many :team_years
end

app/models/team_year.rb
class TeamYear < ActiveRecord::Base
  belongs_to :athletes
  belongs_to :teams
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render action: 'show', status: :created, location: @race }
      else
        format.html { render action: 'new' }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:location_id, :type_id, :name, :date, :competition_id, :sport_id, :global_race_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/team_years_helper.rb
module TeamYearsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/races/_form.html.erb
<%= form_for(@race) do |f| %>
  <% if @race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% @race.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.number_field :location_id %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :competition_id %><br>
    <%= f.number_field :competition_id %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br>
    <%= f.number_field :sport_id %>
  </div>
  <div class="field">
    <%= f.label :global_race_id %><br>
    <%= f.number_field :global_race_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render 'form' %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<h1>Listing races</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Type</th>
      <th>Name</th>
      <th>Date</th>
      <th>Competition</th>
      <th>Sport</th>
      <th>Global race</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.location_id %></td>
        <td><%= race.type_id %></td>
        <td><%= race.name %></td>
        <td><%= race.date %></td>
        <td><%= race.competition_id %></td>
        <td><%= race.sport_id %></td>
        <td><%= race.global_race_id %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render 'form' %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @race.location_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @race.type_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @race.competition_id %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @race.sport_id %>
</p>

<p>
  <strong>Global race:</strong>
  <%= @race.global_race_id %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>