config/routes.rb
Tridb::Application.routes.draw do
  resources :import_results_from_urls

  resources :import_short_ftp_triathlons

  resources :competitions

  resources :team_years

  resources :teams

  resources :classifications

  resources :segment_results

  resources :segments

  resources :sports

  resources :results

  resources :athletes

  resources :races

  

end

app/models/age_category.rb
class AgeCategory < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/age_group.rb
class AgeGroup < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :segment_results
  has_many :team_years
  belongs_to :locations
  belongs_to :teams
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :results
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/global_race.rb
class GlobalRace < ActiveRecord::Base
  has_many :races
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :races
  has_many :athletes
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :locations
  belongs_to :competitions
  belongs_to :sports
  belongs_to :race_types
  belongs_to :global_races
  has_many :segments
  has_many :results
end

app/models/race_type.rb
class RaceType < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :races
  belongs_to :athletes
  belongs_to :classification
  belongs_to :age_group
  belongs_to :age_category
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  has_many :segment_results
  belongs_to :races
  belongs_to :sports
end

app/models/segment_result.rb
class SegmentResult < ActiveRecord::Base
  belongs_to :segments
  belongs_to :athletes
  belongs_to :age_groups
  belongs_to :age_category
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :segments
  has_many :races
  has_many :competitions
  has_many :race_types
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :athletes
  has_many :team_years
end

app/models/team_year.rb
class TeamYear < ActiveRecord::Base
  belongs_to :athletes
  belongs_to :teams
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @result }
      else
        format.html { render action: 'new' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:race_id, :athlete_id, :classification_id, :place, :time, :age_group_id, :class_id)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/team_years_helper.rb
module TeamYearsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :race_id %><br>
    <%= f.number_field :race_id %>
  </div>
  <div class="field">
    <%= f.label :athlete_id %><br>
    <%= f.number_field :athlete_id %>
  </div>
  <div class="field">
    <%= f.label :classification_id %><br>
    <%= f.number_field :classification_id %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.number_field :place %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :age_group_id %><br>
    <%= f.number_field :age_group_id %>
  </div>
  <div class="field">
    <%= f.label :class_id %><br>
    <%= f.number_field :class_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <thead>
    <tr>
      <th>Race</th>
      <th>Athlete</th>
      <th>Classification</th>
      <th>Place</th>
      <th>Time</th>
      <th>Age group</th>
      <th>Class</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.race_id %></td>
        <td><%= result.athlete_id %></td>
        <td><%= result.classification_id %></td>
        <td><%= result.place %></td>
        <td><%= result.time %></td>
        <td><%= result.age_group_id %></td>
        <td><%= result.class_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Race:</strong>
  <%= @result.race_id %>
</p>

<p>
  <strong>Athlete:</strong>
  <%= @result.athlete_id %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @result.classification_id %>
</p>

<p>
  <strong>Place:</strong>
  <%= @result.place %>
</p>

<p>
  <strong>Time:</strong>
  <%= @result.time %>
</p>

<p>
  <strong>Age group:</strong>
  <%= @result.age_group_id %>
</p>

<p>
  <strong>Class:</strong>
  <%= @result.class_id %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>