config/routes.rb
Tridb::Application.routes.draw do
  resources :import_results_from_urls

  resources :import_short_ftp_triathlons

  resources :competitions

  resources :team_years

  resources :teams

  resources :classifications

  resources :segment_results

  resources :segments

  resources :sports

  resources :results

  resources :athletes

  resources :races

  

end

app/models/age_category.rb
class AgeCategory < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/age_group.rb
class AgeGroup < ActiveRecord::Base
  has_many :results
  has_many :segment_results
end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :segment_results
  has_many :team_years
  belongs_to :locations
  belongs_to :teams
end

app/models/classification.rb
class Classification < ActiveRecord::Base
  has_many :results
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/global_race.rb
class GlobalRace < ActiveRecord::Base
  has_many :races
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :races
  has_many :athletes
end

app/models/race.rb
class Race < ActiveRecord::Base
  belongs_to :locations
  belongs_to :competitions
  belongs_to :sports
  belongs_to :race_types
  belongs_to :global_races
  has_many :segments
  has_many :results
end

app/models/race_type.rb
class RaceType < ActiveRecord::Base
  belongs_to :sports
  has_many :races
  has_many :import_results_from_urls
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :races
  belongs_to :athletes
  belongs_to :classification
  belongs_to :age_group
  belongs_to :age_category
end

app/models/segment.rb
class Segment < ActiveRecord::Base
  has_many :segment_results
  belongs_to :races
  belongs_to :sports
end

app/models/segment_result.rb
class SegmentResult < ActiveRecord::Base
  belongs_to :segments
  belongs_to :athletes
  belongs_to :age_groups
  belongs_to :age_category
end

app/models/sport.rb
class Sport < ActiveRecord::Base
  has_many :segments
  has_many :races
  has_many :competitions
  has_many :race_types
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :athletes
  has_many :team_years
end

app/models/team_year.rb
class TeamYear < ActiveRecord::Base
  belongs_to :athletes
  belongs_to :teams
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  before_action :set_segment, only: [:show, :edit, :update, :destroy]

  # GET /segments
  # GET /segments.json
  def index
    @segments = Segment.all
  end

  # GET /segments/1
  # GET /segments/1.json
  def show
  end

  # GET /segments/new
  def new
    @segment = Segment.new
  end

  # GET /segments/1/edit
  def edit
  end

  # POST /segments
  # POST /segments.json
  def create
    @segment = Segment.new(segment_params)

    respond_to do |format|
      if @segment.save
        format.html { redirect_to @segment, notice: 'Segment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @segment }
      else
        format.html { render action: 'new' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segments/1
  # PATCH/PUT /segments/1.json
  def update
    respond_to do |format|
      if @segment.update(segment_params)
        format.html { redirect_to @segment, notice: 'Segment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @segment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segments/1
  # DELETE /segments/1.json
  def destroy
    @segment.destroy
    respond_to do |format|
      format.html { redirect_to segments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segment
      @segment = Segment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segment_params
      params.require(:segment).permit(:race_id, :sport_id, :order, :the_geom, :distance)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/helpers/team_years_helper.rb
module TeamYearsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/segments/_form.html.erb
<%= form_for(@segment) do |f| %>
  <% if @segment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@segment.errors.count, "error") %> prohibited this segment from being saved:</h2>

      <ul>
      <% @segment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :race_id %><br>
    <%= f.number_field :race_id %>
  </div>
  <div class="field">
    <%= f.label :sport_id %><br>
    <%= f.number_field :sport_id %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :the_geom %><br>
    <%= f.text_field :the_geom %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/segments/edit.html.erb
<h1>Editing segment</h1>

<%= render 'form' %>

<%= link_to 'Show', @segment %> |
<%= link_to 'Back', segments_path %>

app/views/segments/index.html.erb
<h1>Listing segments</h1>

<table>
  <thead>
    <tr>
      <th>Race</th>
      <th>Sport</th>
      <th>Order</th>
      <th>The geom</th>
      <th>Distance</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.race_id %></td>
        <td><%= segment.sport_id %></td>
        <td><%= segment.order %></td>
        <td><%= segment.the_geom %></td>
        <td><%= segment.distance %></td>
        <td><%= link_to 'Show', segment %></td>
        <td><%= link_to 'Edit', edit_segment_path(segment) %></td>
        <td><%= link_to 'Destroy', segment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Segment', new_segment_path %>

app/views/segments/new.html.erb
<h1>New segment</h1>

<%= render 'form' %>

<%= link_to 'Back', segments_path %>

app/views/segments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Race:</strong>
  <%= @segment.race_id %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @segment.sport_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @segment.order %>
</p>

<p>
  <strong>The geom:</strong>
  <%= @segment.the_geom %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @segment.distance %>
</p>

<%= link_to 'Edit', edit_segment_path(@segment) %> |
<%= link_to 'Back', segments_path %>